apiVersion: v1
kind: Namespace
metadata:
  name: test-app1
  labels:
    name: test-app1
---
apiVersion: v1
kind: Pod
metadata:
  name: test-app1
  namespace: test-app1
spec:
  containers:
  - name: nginx1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
